#!/bin/bash
#SBATCH -A Sis25_degironc_0
#SBATCH -p boost_usr_prod
#SBATCH --job-name=pmaker_l1
#SBATCH --output=sbatch/jobouts/%x.%j.out
#SBATCH --error=sbatch/joberrs/%x.%j.err
#SBATCH --mem=100000MB
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --time 1-00:00:00

# Variables
maindir=pacemaker/Tr1k_n/border_L1
subfolders=(b_order2 b_order3 b_order4)

# Load modules
. ~/bin/module_load_ace

# Your commands here
date

for test in "${subfolders[@]}"; do
    echo "Running test in $test"
    cd $maindir/$test
    pacemaker input.yaml 
done

date

